version: '3.4'

services:
  inventory.api:
    image: inventoryapi:dev
    container_name: Inventory.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Inventory.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_inventory.api$
    volumes:
      - C:\Users\Kugan\Downloads\Basic.MS2\Basic.MS\Inventory.Api:/app
      - C:\Users\Kugan\Downloads\Basic.MS2\Basic.MS:/src
      - C:\Users\Kugan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_inventory.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_inventory.api$ \"/app/bin/Debug/netcoreapp3.1/Inventory.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  order.api:
    image: orderapi:dev
    container_name: Order.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Order.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_order.api$
    volumes:
      - C:\Users\Kugan\Downloads\Basic.MS2\Basic.MS\Order.Api:/app
      - C:\Users\Kugan\Downloads\Basic.MS2\Basic.MS:/src
      - C:\Users\Kugan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_order.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_order.api$ \"/app/bin/Debug/netcoreapp3.1/Order.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  report.api:
    image: reportapi:dev
    container_name: Report.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Report.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_report.api$
    volumes:
      - C:\Users\Kugan\Downloads\Basic.MS2\Basic.MS\Report.Api:/app
      - C:\Users\Kugan\Downloads\Basic.MS2\Basic.MS:/src
      - C:\Users\Kugan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_report.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_report.api$ \"/app/bin/Debug/netcoreapp3.1/Report.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  webgw:
    image: webgw:dev
    container_name: GatewayBase
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "GatewayBase"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webgw$
    volumes:
      - C:\Users\Kugan\Downloads\Basic.MS2\Basic.MS\GatewayBase:/app
      - C:\Users\Kugan\Downloads\Basic.MS2\Basic.MS:/src
      - C:\Users\Kugan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webgw$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webgw$ \"/app/bin/Debug/netcoreapp3.1/GatewayBase.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
