version: '3.4'

services:

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Inventory.Api/Dockerfile
    ports:
      - "7297"

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order.Api/Dockerfile
    ports:
      - "7298"
  
  report.api:
    image: ${DOCKER_REGISTRY-}reportapi
    build:
      context: .
      dockerfile: Report.Api/Dockerfile
    ports:
      - "7299"

  webgw:
    image: ${DOCKER_REGISTRY-}webgw
    build: 
      context: .
      dockerfile: GatewayBase/Dockerfile